# Generated by Django 3.0.1 on 2019-12-27 14:46

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CH', 'Challenge Court'), ('TR', 'Training Court'), ('TI', 'Timebase Court')], default='TI', max_length=2)),
                ('time_on_court', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('court_end_time', models.DateTimeField()),
                ('on_court', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('wait_list', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None)),
            ],
        ),
    ]
